
-- This file has been generated by the CAVI-ART CLIR-to-Haskell transformer tool

{-# LANGUAGE DeriveGeneric #-}
module UUT where


import qualified Arrays as A
import qualified Bags as B
import qualified Sets as S
import qualified Sequences as Q
import Assertion
import Data.List
import GHC.Generics

data T = Uno Int | Dos Char
         deriving Generic


uutNargs :: Int
uutNargs = 3

uutMethods :: [String]
uutMethods = ["uutPrec", "uutMethod", "uutPost"]

uutName :: String
uutName = "insert" --TODO usar al principio del output

uutPrec :: Int -> Char -> T -> Bool
uutPrec n c t = True

uutMethod :: Int -> Char -> T -> T
uutMethod n c (Uno x) = Dos c
uutMethod n c (Dos y) = Uno n


uutPost :: Int -> Char -> T -> T -> Bool
uutPost n c t o = True


